spring.application.name=notification_service

server.port=8090

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-service
sendgrid.api.key=ZN3948FHQXECD37J1BY7WDY5

to-email=arunjavaop@gmail.com
